# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-18 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import utils.renameImg


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20181018_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='source_img',
            field=models.ImageField(blank=True, default='blog/images/default.png', null=True, storage=utils.renameImg.ImageStorage(), upload_to='blog/images/', verbose_name='封面图片'),
        ),
    ]
