# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181010_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_type',
            field=models.IntegerField(choices=[(0, '未登录'), (1, '登录未人脸认证'), (2, '登录已人脸认证')], default=0, help_text='登录类型', verbose_name='登录类型'),
        ),
    ]
