# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-15 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_login_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='knowfacecode',
            field=models.TextField(blank=True, default='', null=True, verbose_name='用户人脸矩阵'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='login_type',
            field=models.IntegerField(choices=[(0, '未登录'), (1, '未人脸认证'), (2, '已人脸认证')], default=0, help_text='登录类型', verbose_name='登录类型'),
        ),
    ]
