# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 17:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourcesCore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='资源ID')),
                ('sourcename', models.CharField(max_length=100, verbose_name='资源名称')),
                ('sourceurl', models.URLField(verbose_name='资源地址')),
                ('code', models.CharField(max_length=20, verbose_name='提取码')),
                ('send_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '资源集合',
                'verbose_name_plural': '资源集合',
            },
        ),
    ]
