# Generated by Django 2.2.8 on 2020-05-22 12:58

import datetime
from django.db import migrations, models
import utils.renameImg


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceLimit',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('num_count', models.IntegerField(default=50, verbose_name='次数')),
                ('limit_time', models.DateField(default=datetime.date.today, verbose_name='有效时间')),
            ],
            options={
                'verbose_name': '次数管理',
                'verbose_name_plural': '次数管理',
            },
        ),
        migrations.CreateModel(
            name='SourcesCore',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='资源ID')),
                ('sourcename', models.CharField(max_length=100, verbose_name='资源名称')),
                ('sourceurl', models.URLField(blank=True, help_text='可不填，会自动从资源描述里读取', null=True, verbose_name='资源地址')),
                ('code', models.CharField(blank=True, help_text='可不填，会自动从资源描述里读取', max_length=20, null=True, verbose_name='提取码')),
                ('sourcedesc', models.CharField(blank=True, help_text='默认是百度云的资源，如果不是，上面两个请填写', max_length=200, null=True, verbose_name='综合描述')),
                ('question_type', models.IntegerField(choices=[(1, '视频资源'), (2, '专业资源'), (3, '软件资源'), (0, '其他资源')], default=0, help_text='资源类型', verbose_name='资源类型')),
                ('source_img', models.ImageField(blank=True, default='sources/images/default.png', null=True, storage=utils.renameImg.ImageStorage(), upload_to='sources/images/', verbose_name='资源图片')),
                ('send_time', models.DateField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '资源集合',
                'verbose_name_plural': '资源集合',
            },
        ),
    ]
