# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-14 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescore',
            name='sourcedesc',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='综合描述'),
        ),
        migrations.AlterField(
            model_name='sourcescore',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='提取码'),
        ),
        migrations.AlterField(
            model_name='sourcescore',
            name='sourceurl',
            field=models.URLField(blank=True, null=True, verbose_name='资源地址'),
        ),
    ]
