# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-17 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0002_auto_20180914_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescore',
            name='question_type',
            field=models.IntegerField(choices=[(1, '视频资源'), (2, '专业资源'), (3, '软件资源'), (0, '其他资源')], default=0, help_text='资源类型', verbose_name='资源类型'),
        ),
    ]
