# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-22 00:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0004_auto_20180921_2359'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sourcelimit',
            options={'verbose_name': '次数管理', 'verbose_name_plural': '次数管理'},
        ),
    ]
