# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-10-10 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import utils.renameImg


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0005_auto_20180922_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcescore',
            name='source_img',
            field=models.ImageField(blank=True, default='sources/images/default.png', null=True, storage=utils.renameImg.ImageStorage(), upload_to='sources/images/', verbose_name='资源图片'),
        ),
    ]
